name: MasterRA
 
on:
  push:
    branches: ["master"]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Dev Repository
      uses: actions/checkout@v4
 
    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: abinsk/testaction2
        path: test-repo
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
 
    # - name: Install dependencies
    #   run: |
    #     cd test-repo
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
 
    - name: Run Tests
      run: |
        cd test-repo
        testit.py
        
